WITH cte AS 
(
    SELECT a1.PLAYER_ID
    FROM ACTIVITY a1
    JOIN ACTIVITY a2 ON a1.PLAYER_ID = a2.PLAYER_ID AND DATEDIFF(a2.EVENT_DATE, a1.EVENT_DATE) = 1
    WHERE (a1.PLAYER_ID, a1.EVENT_DATE) IN (SELECT PLAYER_ID, MIN(EVENT_DATE) FROM ACTIVITY GROUP BY PLAYER_ID)
)

SELECT ROUND(COUNT(PLAYER_ID)/(SELECT COUNT(DISTINCT(PLAYER_ID)) FROM ACTIVITY),2) AS FRACTION
FROM cte